# Setup
title:        c0ldfashioned.net
tagline:      Occasional Outbursts of Noise
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Charlie
  url:        "http://c0ldfashioned.net"

# Gems
gems:
  - jekyll-paginate
  - jekyll-jupyter-notebook
#From original build
include: ['_pages']
twitter_username: cold_fashioned
github_username:  coldfashioned
#Others
markdown: kramdown
highlighter: rouge
# plugins
plugins: ['jekyll-twitter-plugin']
