# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: c0ldfashioned.net

description: > # this means to ignore newlines until "baseurl:"
  A site for blogging. You might see some of my music,
  DIY stuff or other random noise on here.
  Tweet if you made it this far, and let me know where you're from!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://c0ldfashioned.net" # the base hostname & protocol for your site
twitter_username: cold_fashioned
github_username:  coldfashioned
include: ['_pages']
# Build settings
markdown: kramdown
