# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: c0ldfashioned's dungeon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All posts are my own. All content owned by me. Drop me an email
  if you made it this far, and let me know where you're from. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://c0ldfashioned.net" # the base hostname & protocol for your site
twitter_username: cold_fashioned
github_username:  coldfashioned

# Build settings
markdown: kramdown
